### ISSUE TITLE
Alt+Tabbing issue (Interaction with DisplayFusion)

### ISSUE THREAD

**Issue by Daniele-f** [RamonUnch/AltDrag#30] opened 2021-02-26 17:16 UTC
Hi,

When I Alt+Tab, the Alt button 'stays active' until I press the Alt button again on my keyboard.

v. 1.37

**Comment by RamonUnch** [comment] 2021-02-26 18:07
I need a bit more information actually. 
Does this happens when using Tha Alt+Tab normally with the Keyboard or with the Alt+Tab scroll action?
Could you give me a copy of your ini file?
Does it happen every time?
Does pressing Escape works too?
Which version of windows are you using?
Also does it happen with previous 1.35 or latest 1.38?

**Comment by Daniele-f** [comment] 2021-02-27 00:18
Hi,
- I'm using my keyboard.
- (had to add.txt to the .ini file to upload it here)
- yes every time altdrag.exe is running (it doesn't happen when it's not running)
- Esc doesn't help.
- I'm using Windows 10 x64
- I just downloaded & installed 1.38 and it still happens.

[AltDrag.ini.txt](https://github.com/RamonUnch/AltDrag/files/6053348/AltDrag.ini.txt)

**Comment by RamonUnch** [comment] 2021-02-27 08:53
Ok thanks, I will check this out.
It is really strange because Win10 x64 is my primary test platform and I could not reporduce it here.
In the meantime, a solution that may help is to use the WinKey as a hotkey instead of Alt.

**Comment by RamonUnch** [comment] 2021-02-27 10:02
I really can not reproduce, do you use any other keyboard/mouse input filters such as AutoHotKeys that might interact?
When you say that Alt is stuck do you mean that AltDrag is still activated and will drag windows when you click on them or Alt is stuck without altdrag being activated and you get stuck in the programs menu?
Could you try with this version of hooks.dll that will create the "ad.log" file. This log should contain every instances of Hotkey DOWN and Hotkey UP.

If everything is going normally, after using AltDrag for some time, the log should always contain a DOWN and UP alternance. if it does not then it means some program in the keyboard hook chain is not forwarding the input.
[hooks_log.zip](https://github.com/RamonUnch/AltDrag/files/6054140/hooks_log.zip)

**Comment by Daniele-f** [comment] 2021-02-28 00:26
I did some more troubleshooting, and I found it only happens when I use AltDrag with [DisplayFusion](https://www.displayfusion.com/).
I've contacted their support team just now.

**Comment by RamonUnch** [comment] 2021-02-28 07:15
I will have a lookat this myself, Maybe AltDrag can be can be more careful, and avoid interaction with this one.

**Comment by RamonUnch** [comment] 2021-03-01 15:30
I tried both on an old WinXP machine with the old DisplayFusion v8.1.2 qnd using Win10 20H2 with DisplayFusionv 9.7.1. and and I could not reproduce the bug. Maybe it only happens with specific settings...

Under Windows 10, I do not see much benefit from the DisplayFusion Alt+Tab because Windows 10 has clickable thumbnail on its default Alt+Tab, so maybe an other solution for you would be to disable this Alt+Tab under DisplayFusion 
In [DisplayFusion]->Settings->Alt+Tab->Disabled.

**Comment by Daniele-f** [comment] 2021-03-01 15:40
Thank you for looking into it.

Disabling that option did indeed solve this issue (the only difference is that the thumbnails only show on the primary monitor by default, but I can live with that 😄)

I'll keep you updated when they reply to my ticket.

**Comment by RamonUnch** [comment] 2021-03-01 16:09
I checked more in details and actually the problem is that I tested under Windows 10 with the portable version that behaves slightly differently because it does not elevate as administrator by default.

So actually it is not really a bug of DisplayFusion or AltDrag but a problem of mixing with admin and non admin privileges for keyboard access.

The solution is to Elevate AltDrag:
AltDrag->Configure->General->Autostart: "Elevate to administrator proivileges" (very bottom) and click the Elevate button.

Then you should be able to use The Alt+Tab of DisplayFusion together with AltDrag.

**Comment by RamonUnch** [comment] 2021-03-02 08:35
Actually I can fix the problem by disabling AltDrag on the Tab Down event. This will also avoid AltDrag interaction with that Alt+Tab window that you can no longer click because Alt is down.
Try this version of hooks.dll  (replace the one that is in your AltDrag directory after quitting AltDrag.

[hooks.zip](https://github.com/RamonUnch/AltDrag/files/6067255/hooks.zip)

It will be in next release.

**Comment by RamonUnch** [comment] 2021-03-05 18:04
In next build you will have the ability to add Killkeys that will disable Alt on the key down.
It contains TAB by default and you will be able to add any other keys.

**Closed by RamonUnch** 2021-03-05 18:04 UTC
Labels: bug
