### ISSUE TITLE
Mouse Cursor Very Laggy on Windows Startup/Invisible cursor

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltDrag#15] opened 2021-01-18 15:35 UTC
This has only happened the once, but on logging in to my rebooted system, the mouse was very laggy and delayed in control. Windows itself was fine and snappy, and only as soon as I quit AltDrag did the mouse return to its expected behavior.

I have AltDrag set up to run on login via Task Scheduler and to elevate the program. Also, it may be limited to behavior in one of the recent `hooks.dll` that you have provide me.

Interestingly, after killing the program and re-running it via the task schedule, it's performing fine. Maybe it only occurs on start-up? I'll have to keep an eye out if it happens again.

Thanks.

```
AltDrag 1.32 (dev hooks.dll)
Windows 10 20H2
```

**Comment by RamonUnch** [comment] 2021-01-18 15:53
Maybe upgrade to the later v1.34...
And tell me if it happens again in the future.

**Comment by RamonUnch** [comment] 2021-01-22 10:50
By reviewing old issues on the original AltDrag, I found this one: https://github.com/stefansundin/altdrag/issues/77
The trick is to add a delay so that AltDrag is not lunched immediately at logon.

**Comment by RamonUnch** [comment] 2021-01-31 09:51
After thinking a little more I think this may have beed due to the infinite loop that may occure in the Tray icon handeling. this was fixed with 1.33. This was an AltDrag.exe bug so it makes sense that you encountered using v1.32.
Has any one encountered this problem again?

**Comment by redactedscribe** [comment] 2021-01-31 12:02
I've delayed the process on start-up, but I did notice something else which I never had before: my cursor was invisible and I believe it had to do with AltDrag. Haven't seen it since (I don't reboot regularly).

**Comment by RamonUnch** [comment] 2021-02-03 08:03
The only way AltDrag could interact with mouse cursor is through a small invisible window that will diseappear on ESC, or on a click, 
AltDrag does not change the system cursors,it just creates this small invisible window that tell which cursor should be shown when the mouse pointer is in on its top.
I had invisible cursors on bood with Win10 regularry without altdrag in autostart because of buggy mouse and/or bad usb connection.

**Comment by redactedscribe** [comment] 2021-02-03 12:46
I just woke my PC from hibernation and experienced an invisible mouse cursor again.

I managed to close AltDrag via the system tray icon, and when launching the executable again, the cursor returned.

I'm fairly positive it's related to AltDrag in some way.

**Comment by RamonUnch** [comment] 2021-02-03 15:50
The cursor returned when lunching AltDrag not quitting?
You closed AltDrag via the tray, so you could still click, the cursor was just invisible?
Could you try with UseCursor=0 in the [Advanced] section of AltDrag.ini

Could you find a sequence to reproduce, because I tried to sleep awake on three different computers (Win10 20H2, Win10 2004, and Win8.1) more that twenty times on each without experiencing this issue.

**Comment by redactedscribe** [comment] 2021-02-03 17:58
The cursor returned when I launched AltDrag, yes. Not when quitting. But it could be there was some kind of delay. I will have to pay more attention. The icons in the tray highlight when you go over them so I was able to right-click AltDrag this way.

I am a bit busy unfortunately, but I'll try keep a track if it happens now that `UseCursor=0`.

**Comment by redactedscribe** [comment] 2021-02-21 13:51
I haven't, though I don't think the testing is conclusive yet as it may have been caused by another program on my system.

The AltDrag ini option is still set to `0` and now the other program is set back to its original setting. This way I will know if it is the other program or the ini setting. If you ask me in another week, I can probably tell you a more accurate answer.

**Comment by redactedscribe** [comment] 2021-03-01 11:55
I haven't noticed the bug since setting `UseCursor=0`. I will set it to `1` now and see if I encounter it again (using v`1.38`).

**Comment by RamonUnch** [comment] 2021-07-02 08:34
I will consider it closed (open a new one if you get again similar problems).

**Closed by RamonUnch** 2021-07-02 08:34 UTC
Labels: bug
