### ISSUE TITLE
Bug: Resizing a window can lead to it being cropped

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltDrag#16] opened 2021-01-27 16:09 UTC
![altdrag-window-offset](https://user-images.githubusercontent.com/25013746/106018536-4b6c9680-60ca-11eb-9abc-73306aeeaeb7.jpg)
The black borders are actually the window's area, but the entire window is offset (I did not cut off part of the image). Where you see my cursor in the screenshot, it actually selected the line below and a little to the right.

Not sure of the steps to reproduce, but thought I'd mention this here.

(The window is only running as administrator because I was running AltDrag as admin and opened its config file via middle-clicking its tray icon.)

AltDrag 1.35

**Comment by RamonUnch** [comment] 2021-01-27 21:23
Someone presented a similar issue with original AltDrag https://github.com/stefansundin/altdrag/issues/119
I thought I had fixed it by veryfying that the window would respond to WM_NULL message in a resonable time, However it seems that some applications give a bad window handle when asking them for the "parent" window.

I donot know to this day a way to avoid this at 100% and because it is very rare and only happens with some specific applications, I am not sure when I will be able to figure this out.

**Comment by hi2u** [comment] 2021-01-28 04:30
Just to add what I knew of the issue:

* I've only just heard about this fork today, and installed 1.35 - and looking good so far, I haven't been able to trigger the issue yet
* When I was seeing the issue on the stefansundin version: I'm pretty sure that I only ever saw it in Chrome/Chromium/Electron based software - so that's something that is worth reporting (whether it is chromium/electron based windows having the issue)
* Typically I could intentionally trigger it in Chrome or Vscode by just doing 10-30 seconds of violent shaking of the mouse while holding ALT + right-mouse-button for a window resize
* I've just been running AltDrag + the rest of my windows as my normal Windows user (not admin) - so not sure if that makes a difference here, but worth mentioning if anyone is reporting
* Will report back if I see the issue in this fork

**Comment by RamonUnch** [comment] 2021-02-03 08:06
> Typically I could intentionally trigger it in Chrome or Vscode by just doing 10-30 seconds of violent shaking of the mouse while holding ALT + right-mouse-button for a window resize

So it means that potentially increasing the values for RefreshRate and/or ResizeRate could help in this regard.

**Comment by hi2u** [comment] 2021-02-04 06:43
### Moves on any version:

> did it ever happen for a Move?

No I don't remember ever seeing the problem during a window move. Although I'm not 100% sure... maybe 95% sure though...

I just temporarily reinstalled v1.11 for a few minutes to try it out... and couldn't cause the problem via a window move, only resizes.

### One occurrence for resizes on v1.35:

Although funnily enough, after doing that and restoring back to v1.35 again, I did manage to get it to cause the problem for the 1st (and only) time via a window resize.  And I did confirm that v1.35 was running, by right-clicking the tray icon and checking "About".

See the black bar to the left:
![image](https://user-images.githubusercontent.com/9689599/106854708-804e9e00-6707-11eb-824e-e958f11ce918.png)

I haven't been able to trigger it a 2nd time though.  

So for my computer at least, I guess either:

- a) v1.35 does very occasionally have the problem, but this is the only one time I've seen it
- b) or maybe it was just related to be swapping between versions within the space of a short period, and without rebooting... library/process still in memory or something?   Although I was checking the "About" window to confirm what version was running.

**Comment by RamonUnch** [comment] 2021-04-01 09:53
Maybe, the problem is related to MDI windows.
Try to disable MDI support or to add the window to the MDIs balcklist, and tell me if you are able to have this problem again.

**Comment by hi2u** [comment] 2021-04-16 04:32
Since my last post above in Feb, I haven't noticed the the issue at all until today.  But I just saw it once now in Chrome:

![2021-04-16_143108-Window](https://user-images.githubusercontent.com/9689599/114971795-75ab4480-9ec0-11eb-87f2-50052a48622b.png)

The red border is my desktop background to make it clear where the issue is (the vertical black bar on the right, and some of the left of the window is cut off).

However note that I was still on version 1.35, so not sure if it has already been fixed in newer versions.  

I'll upgrade to 1.42 and let you know if I see it again.

**Comment by RamonUnch** [comment] 2021-04-16 12:51
I expect v1.42 to have similar issue, but is seems quite rare anyway.

**Comment by RamonUnch** [comment] 2021-05-03 13:31
I found a way to trigger this bug:
1) Open Chrome or similar
2) Keep ALT down and resize a corner while clicking many times along your movement.

This will resize by steps and sometime when doing it fast it triggers the bug.
Now that I have a way to reproduce I hope I will be able to fix it.
It already seems that if you increase the RefreshRate and the ResizeRate values in the [Advanced] section of the ini file it is harder to trigger the bug.

**Comment by RamonUnch** [comment] 2021-05-03 14:37
Could you try with this version of AltDrag+Hooks.dll
[AltDrag1.43rc3bin.zip](https://github.com/RamonUnch/AltDrag/files/6415497/AltDrag1.43rc3bin.zip)
I can no longer trigger the problem using this one...

**Comment by RamonUnch** [comment] 2021-05-10 10:56
@hi2u @redactedscribe 
crop bug should be fixed with latest 1.43!

**Closed** 2021-05-10 14:16 UTC
Labels: bug
